SportsBetting.Web/Areas/Admin/Controllers/LeagueController.cs
namespace SportsBettingSystem.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    
    using Services.Interfaces;
    using ViewModels.League;
	public class LeagueController : BaseAdminController
	{
		private readonly ILeagueService leagueService;
		public LeagueController(ILeagueService leagueService)
		{
			this.leagueService = leagueService;
		}
		[HttpGet]
		public IActionResult Create()
		{
			var leagueFormModel = new LeagueFormModel();

			return View(leagueFormModel);
		}

		[HttpPost]
		public async Task<IActionResult> Create(LeagueFormModel model)
		{
			if (!this.ModelState.IsValid)
			{
				return this.View(model);
			}
			try
			{
				await leagueService.CreateAsync(model);
			}
			catch (Exception)
			{
				this.ModelState
					.AddModelError(string.Empty, "Unexpected error occurred while trying to add new league! Please try again later or contact administrator!");
				return this.View(model);
			}
			return this.RedirectToAction("Index", "Home", new { area = "Admin" });
		}
	}
}

SportsBetting.Web/Areas/Admin/Controllers/TeamController.cs
namespace SportsBettingSystem.Web.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.Team;
    public class TeamController : BaseAdminController
    {
        private readonly ILeagueService _leagueService;
        private readonly ITeamService _teamService;
        public TeamController(ILeagueService leagueService, ITeamService teamService)
        {
            this._leagueService = leagueService;
            this._teamService = teamService;
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View(new TeamFormModel()
            {
                Leagues = await _leagueService.AllLeaguesAsync()
            });
        }
        [HttpPost]
        public async Task<IActionResult> Create(TeamFormModel model)
        {
            if (!await _teamService.LeagueExistsAsync(model.LeagueId))
            {
                this.ModelState.AddModelError(nameof(model.LeagueId), "League does not exist");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await _teamService.CreateTeamAsync(model);

            return this.RedirectToAction("Index", "Home", new {area = "Admin"});
        }
    }
}

SportsBetting.Web/Controllers/GameController.cs
namespace SportsBettingSystem.Web.Controllers
{
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.EntityFrameworkCore;
	
	using Data;
	using Services.Interfaces;
	using ViewModels.Game;

    public class GameController : Controller
    {
        private readonly ILeagueService leagueService;
        private readonly IGameService gameService;

        public GameController(IGameService gameService, ILeagueService leagueService)
        {
            this.gameService = gameService;
            this.leagueService = leagueService;

        }

        [HttpGet]
        public async Task<IActionResult> Show()
        {
            GameServiceModel model = new()
            {
                Date = DateTime.Now,
                AllGames = await gameService.AllGamesAsync(),
                Leagues = await leagueService.AllLeaguesAsync(),
                Games = await gameService.FilterByLeagueAndDateAsync(-1, DateTime.UtcNow)
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetGamesByLeagueAndDate(int leagueId, double days)
        {
	        if (days > 6)
		        return Json(0);
            var filteredGames = await gameService.FilterByLeagueAndDateAsync(leagueId, DateTime.UtcNow.AddDays(days));
            return Json(filteredGames);
        }
    }
}

SportsBetting.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using SportsBettingSystem.Data.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
@{
    string year = "";
    if (DateTime.UtcNow.Year > 2023) year = "- " + DateTime.UtcNow.Year.ToString();
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoftBet</title>
    <link rel="stylesheet" href="~/css/nav_button_style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/logoutButton.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
	            <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">SoftBet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="myElement" class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
	                <ul class="navbar-nav flex-grow-1">
		                <li class="nav-item">
			                <button id="myElement">
				                <a class="button_top nav-link text-dark" asp-area="Admin" asp-controller="League" asp-action="Create">Create League</a>
			                </button>
		                </li>
		                <li class="nav-item">
			                <button id="myElement">
				                <a class="button_top nav-link text-dark" asp-area="Admin" asp-controller="Team" asp-action="Create">Create Team</a>
			                </button>
		                </li>
		                <li class="nav-item">
			                <button id="myElement">
				                <a class="button_top nav-link text-dark" asp-area="Admin" asp-controller="Game" asp-action="Create">Create Game</a>
			                </button>
		                </li>
		                <li class="nav-item">
			                <button id="myElement">
				                <a class="button_top nav-link text-dark" asp-area="Admin" asp-controller="Game" asp-action="ShowGamesForUpdate">Update Games</a>
			                </button>
		                </li>
		                <li class="nav-item">
			                <button id="myElement">
				                <a class="button_top nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Show">Show Games</a>
			                </button>
		                </li>
	                </ul>
	                @if (SignInManager.IsSignedIn(User))
	                {
		                <li class="nav-item">
			                <form  class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
								<button type="submit" class="nav-link btn btn-link text-dark logoutbtn">Logout</button>
			                </form>
		                </li>
	                }
	                else
	                {
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
		                </li>
		                <li class="nav-item">
			                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
		                </li>
	                }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;SoftBet 2023 @year
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>